[tool.poetry]
name = "hexlet_pytest"
version = "0.1.0"
description = ""
authors = ["Badrkic Boris <zebrnjak88@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
